# Generated by Django 6.0.2 on 2026-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourite_destination',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
