# Generated by Django 6.0.2 on 2026-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysubmission',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
