# Generated by Django 4.2.11 on 2026-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_3',
            field=models.URLField(blank=True),
        ),
    ]
