# Generated by Django 4.2.11 on 2026-03-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_cover_image_2_post_cover_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='story_submissions/'),
        ),
    ]
